version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploaded_images:/app/uploaded_images

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
